2025-04-29 13:12:34,000 - trading_system.historical_data_collector_binanceusdm - ERROR - [historical_data_collector.py:135] - Lỗi khi kiểm tra cặp giao dịch BTC/USDT: 'BinanceConnector' object has no attribute 'markets'
2025-04-29 13:12:34,004 - trading_system.historical_data_collector_binanceusdm - ERROR - [historical_data_collector.py:135] - Lỗi khi kiểm tra cặp giao dịch BTC/USDT: 'BinanceConnector' object has no attribute 'markets'
2025-04-29 13:12:34,006 - trading_system.historical_data_collector_binanceusdm - ERROR - [historical_data_collector.py:135] - Lỗi khi kiểm tra cặp giao dịch BTC/USDT: 'BinanceConnector' object has no attribute 'markets'
2025-04-29 13:12:34,008 - trading_system.historical_data_collector_binanceusdm - ERROR - [historical_data_collector.py:135] - Lỗi khi kiểm tra cặp giao dịch ETH/USDT: 'BinanceConnector' object has no attribute 'markets'
2025-04-29 13:12:34,011 - trading_system.historical_data_collector_binanceusdm - ERROR - [historical_data_collector.py:135] - Lỗi khi kiểm tra cặp giao dịch ETH/USDT: 'BinanceConnector' object has no attribute 'markets'
2025-04-29 13:12:34,014 - trading_system.historical_data_collector_binanceusdm - ERROR - [historical_data_collector.py:135] - Lỗi khi kiểm tra cặp giao dịch ETH/USDT: 'BinanceConnector' object has no attribute 'markets'
